In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import seaborn as sns

In [2]:
hcv_1 = pd.read_csv("../Resultat/half_HCV_1.csv", sep=';')

In [3]:
hcv_2 = pd.read_csv("../Resultat/HCV_CLEAN_ORIG.csv", sep=';')

In [4]:
hcv_1

,Dataset,Support,Size,Temps d'exécution (s),Mémoire maximale (Ko),Titre variables,Supports motifs,Motifs detectés
0,./data/Clean/HCV.csv,0.04,4716,903.876701,3546.357422,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.06820793940838431, 0.062397711925001986, 0....","[{'11-', '1+', '2+', '3-'}, {'1+', '2+', '5-',..."
1,./data/Clean/HCV.csv,0.08,2216,205.292393,1349.550781,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.13503350017213528, 0.13334922274304176, 0.1...","[{'6+', '5-', '4+'}, {'5-', '7-', '4+'}, {'5-'..."
2,./data/Clean/HCV.csv,0.10,1525,100.696959,877.844727,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.1534652154339133, 0.17029739678504277, 0.13...","[{'11-', '1+', '2+'}, {'2-', '11+', '1+'}, {'5..."
3,./data/Clean/HCV.csv,0.14,813,36.768094,383.610352,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.18980959190699398, 0.1900744154021345, 0.18...","[{'3-', '1+', '2+'}, {'4-', '1+', '2+'}, {'5-'..."
4,./data/Clean/HCV.csv,0.18,589,23.931488,210.571289,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.29980667884854745, 0.24869044781653027, 0.1...","[{'5-', '4+'}, {'3+', '1+', '2+'}, {'3-', '1+'..."
5,./data/Clean/HCV.csv,0.16,697,27.840455,283.805664,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.18980959190699398, 0.1900744154021345, 0.18...","[{'3-', '1+', '2+'}, {'4-', '1+', '2+'}, {'5-'..."
6,./data/Clean/HCV.csv,0.20,496,20.052196,167.610352,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.33316914276634624, 0.29980667884854745, 0.2...","[{'11-', '2+'}, {'5-', '4+'}, {'3+', '1+', '2+..."
7,./data/Clean/HCV.csv,0.24,272,13.089063,87.680664,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.33316914276634624, 0.29980667884854745, 0.3...","[{'11-', '2+'}, {'5-', '4+'}, {'9-', '4+'}, {'..."
8,./data/Clean/HCV.csv,0.28,176,10.491139,52.192383,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.42328328169275176, 0.41834167527343025, 0.4...","[{'3-', '1+'}, {'8-', '1+'}, {'4-', '2+'}, {'5..."

In [5]:
hcv_2

,Dataset,Support,Size,Temps d'exécution (s),Mémoire maximale (Ko),Titre variables,Supports motifs,Motifs detectés
0,./data/Clean/HCV.csv,0.04,4716,856.859834,3546.357422,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.06820793940838431, 0.062397711925001986, 0....","[{'1+', '2+', '11-', '3-'}, {'4+', '1+', '2+',..."
1,./data/Clean/HCV.csv,0.08,2216,189.039778,1349.782227,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.13503350017213528, 0.13334922274304176, 0.1...","[{'6+', '4+', '5-'}, {'4+', '5-', '7-'}, {'8-'..."
2,./data/Clean/HCV.csv,0.10,1525,94.282152,877.844727,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.1534652154339133, 0.17029739678504277, 0.13...","[{'1+', '2+', '11-'}, {'1+', '11+', '2-'}, {'1..."
3,./data/Clean/HCV.csv,0.14,813,34.956580,383.610352,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.18980959190699398, 0.1900744154021345, 0.18...","[{'1+', '2+', '3-'}, {'1+', '2+', '4-'}, {'1+'..."
4,./data/Clean/HCV.csv,0.18,589,22.955824,210.505859,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.29980667884854745, 0.24869044781653027, 0.1...","[{'4+', '5-'}, {'1+', '2+', '3+'}, {'1+', '2+'..."
5,./data/Clean/HCV.csv,0.16,697,26.754105,283.516602,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.18980959190699398, 0.1900744154021345, 0.18...","[{'1+', '2+', '3-'}, {'1+', '2+', '4-'}, {'1+'..."
6,./data/Clean/HCV.csv,0.20,496,19.253927,167.610352,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.33316914276634624, 0.29980667884854745, 0.2...","[{'2+', '11-'}, {'4+', '5-'}, {'1+', '2+', '3+..."
7,./data/Clean/HCV.csv,0.24,272,12.649659,87.680664,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.33316914276634624, 0.29980667884854745, 0.3...","[{'2+', '11-'}, {'4+', '5-'}, {'4+', '9-'}, {'..."
8,./data/Clean/HCV.csv,0.28,176,10.110895,51.960938,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.42328328169275176, 0.41834167527343025, 0.4...","[{'1+', '3-'}, {'1+', '8-'}, {'2+', '4-'}, {'2..."
9,./data/Clean/HCV.csv,0.30,150,9.638912,50.364258,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.44004660893514475, 0.42328328169275176, 0.4...","[{'1+', '2+'}, {'1+', '3-'}, {'1+', '6+'}, {'1..."
10,./data/Clean/HCV.csv,0.34,120,9.240743,39.067383,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.44004660893514475, 0.5442652472127327, 0.42...","[{'1+', '2+'}, {'1+', '3+'}, {'1+', '3-'}, {'1..."
11,./data/Clean/HCV.csv,0.38,94,8.967299,30.809570,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.44004660893514475, 0.522957548793729, 0.544...","[{'1+', '2+'}, {'1+', '2-'}, {'1+', '3+'}, {'1..."
12,./data/Clean/HCV.csv,0.40,94,8.862499,30.036133,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.44004660893514475, 0.522957548793729, 0.544...","[{'1+', '2+'}, {'1+', '2-'}, {'1+', '3+'}, {'1..."
13,./data/Clean/HCV.csv,0.50,48,7.565296,20.431641,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.522957548793729, 0.5442652472127327, 0.5486...","[{'1+', '2-'}, {'1+', '3+'}, {'1+', '8+'}, {'1..."
14,./data/Clean/HCV.csv,0.60,7,7.236839,7.542969,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.6504700617038743, 0.6791345568178809, 0.602...","[{'2+', '11+'}, {'4+', '5+'}, {'4+', '7+'}, {'..."
15,./data/Clean/HCV.csv,0.70,0,7.213992,5.231445,0,0,0
16,./data/Clean/HCV.csv,0.60,7,7.222412,7.542969,"['1 : Age', '2 : ALB', '3 : ALP', '4 : ALT', '...","[0.6504700617038743, 0.6791345568178809, 0.602...","[{'2+', '11+'}, {'4+', '5+'}, {'4+', '7+'}, {'..."
17,./data/Clean/HCV.csv,0.70,0,7.196471,5.231445,0,0,0
18,./data/Clean/HCV.csv,0.80,0,7.206565,4.465820,0,0,0
19,./data/Clean/HCV.csv,0.90,0,7.197827,4.747070,0,0,0
20,./data/Clean/HCV.csv,1.00,0,7.053702,4.176758,0,0,0

In [6]:
#hcv_2.to_excel("../data/serveur/HCV.xlsx", index=False)

In [7]:
hcv_pca = pd.read_csv("../Resultat/Half_Pca_hcv.csv", sep=';')

In [8]:
#hcv_pca.head(20).to_excel('../data/serveur/HCV_PCA.xlsx', index=False)

In [9]:
Air_acp = pd.read_csv("../Resultat/Air quality ACP.csv", sep=';')

In [10]:
#Air_acp.to_excel('../data/serveur/Air Quality_PCA.xlsx', index=False)

In [11]:
Air = pd.read_csv("../Resultat/Air_Quality_CLEAN_reverse.csv", sep=';')

In [12]:
#Air.sort_values(by='Support', ascending=True).to_excel("../data/serveur/Air Quality.xlsx", index=False)

In [13]:
check_pca = pd.read_csv("../Chickenpox_origin_reverse_1.csv", sep=';')

In [14]:
check_pca

,Dataset,Support,Size,Temps d'exécution (s),Mémoire maximale (Ko),Titre variables,Supports motifs,Motifs detectés
0,./data/Clean/Chickenpox.csv,0.34,41522,172638.235327,31800.433594,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.34549679734668814, 0.35096079599355795, 0.3...","[{'7+', '4+', '17+', '6+', '1+', '18+'}, {'4+'..."

In [23]:
checck1 = pd.read_csv("../Resultat/Chickenpox_origin_reverse.csv", sep=';')

In [24]:
checck1

,Dataset,Support,Size,Temps d'exécution (s),Mémoire maximale (Ko),Titre variables,Supports motifs,Motifs detectés
0,./data/Clean/Chickenpox.csv,1.00,0,9.308707,6.962891,0,0,0
1,./data/Clean/Chickenpox.csv,0.90,0,9.789552,5.668945,0,0,0
2,./data/Clean/Chickenpox.csv,0.80,1,9.806202,7.034180,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...",[0.8022076613644553],"[{'1+', '14+'}]"
3,./data/Clean/Chickenpox.csv,0.70,117,11.580837,43.151367,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.7574219927784028, 0.7549142894963267, 0.728...","[{'1+', '2+'}, {'1+', '3+'}, {'1+', '4+'}, {'1..."
4,./data/Clean/Chickenpox.csv,0.60,386,17.552623,104.405273,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.6669681793780013, 0.6727925224847588, 0.681...","[{'2+', '18+'}, {'2+', '20+'}, {'3+', '17+'}, ..."
5,./data/Clean/Chickenpox.csv,0.50,2280,144.305780,1281.600586,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.5417815724255595, 0.5384134548208941, 0.525...","[{'18+', '1+', '4+'}, {'18+', '1+', '16+'}, {'..."
6,./data/Clean/Chickenpox.csv,0.40,16067,10529.315486,12136.811523,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.42511086107617974, 0.42213250380567874, 0.4...","[{'13+', '4+', '18+', '6+'}, {'16+', '4+', '18..."
7,./data/Clean/Chickenpox.csv,0.38,22932,30516.866726,17329.897461,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.39770262021900116, 0.39309168192615146, 0.3...","[{'13+', '1+', '18+', '4+', '6+'}, {'1+', '18+..."

In [66]:
checck1o = pd.read_csv("../Resultat/Chickenpox_origin_reverse.csv", sep=';')

In [71]:
checck1of = pd.read_csv("../Chickenpox_origin_reverse_1.csv", sep=';')

In [72]:
checck1o

,Dataset,Support,Size,Temps d'exécution (s),Mémoire maximale (Ko),Titre variables,Supports motifs,Motifs detectés
0,./data/Clean/Chickenpox.csv,0.34,41522,172638.235327,31800.433594,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.34549679734668814, 0.35096079599355795, 0.3...","[{'7+', '4+', '17+', '6+', '1+', '18+'}, {'4+'..."

In [77]:
pd.concat([checck1,checck1o ], axis=0).sort_values("Support").to_excel("../data/serveur/Chickenpox.xlsx", index=False)

In [25]:
checck2 = pd.read_csv("../Chickenpox_origin_reverse_1.csv", sep=';')

In [26]:
chick  = pd.concat([checck1, checck2], axis = 0)

In [27]:
chick

,Dataset,Support,Size,Temps d'exécution (s),Mémoire maximale (Ko),Titre variables,Supports motifs,Motifs detectés
0,./data/Clean/Chickenpox.csv,1.00,0,9.308707,6.962891,0,0,0
1,./data/Clean/Chickenpox.csv,0.90,0,9.789552,5.668945,0,0,0
2,./data/Clean/Chickenpox.csv,0.80,1,9.806202,7.034180,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...",[0.8022076613644553],"[{'1+', '14+'}]"
3,./data/Clean/Chickenpox.csv,0.70,117,11.580837,43.151367,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.7574219927784028, 0.7549142894963267, 0.728...","[{'1+', '2+'}, {'1+', '3+'}, {'1+', '4+'}, {'1..."
4,./data/Clean/Chickenpox.csv,0.60,386,17.552623,104.405273,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.6669681793780013, 0.6727925224847588, 0.681...","[{'2+', '18+'}, {'2+', '20+'}, {'3+', '17+'}, ..."
5,./data/Clean/Chickenpox.csv,0.50,2280,144.305780,1281.600586,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.5417815724255595, 0.5384134548208941, 0.525...","[{'18+', '1+', '4+'}, {'18+', '1+', '16+'}, {'..."
6,./data/Clean/Chickenpox.csv,0.40,16067,10529.315486,12136.811523,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.42511086107617974, 0.42213250380567874, 0.4...","[{'13+', '4+', '18+', '6+'}, {'16+', '4+', '18..."
7,./data/Clean/Chickenpox.csv,0.38,22932,30516.866726,17329.897461,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.39770262021900116, 0.39309168192615146, 0.3...","[{'13+', '1+', '18+', '4+', '6+'}, {'1+', '18+..."
0,./data/Clean/Chickenpox.csv,0.34,41522,172638.235327,31800.433594,"['1 : BUDAPEST', '2 : BARANYA', '3 : BACS', '4...","[0.34549679734668814, 0.35096079599355795, 0.3...","[{'7+', '4+', '17+', '6+', '1+', '18+'}, {'4+'..."

In [56]:
chekpca1 = pd.read_csv("../Resultat/results_gradual_all.csv", sep=';')

In [57]:
chekpca2 = pd.read_csv("../Resultat/results_gradual_Chickenpox_PCA.csv", sep=';')

In [58]:
chekpca1.columns

Index(['Dataset', 'Support', 'Size', 'Temps d'exécution (s)',
       'Mémoire maximale (Ko)', 'Titre variables', 'Supports motifs',
       'Motifs detectés'],
      dtype='object')

In [59]:
chekpca2.columns

Index(['Dataset', 'Support', 'Size', 'Temps d'exécution (s)',
       'Mémoire maximale (Ko)', 'Titre variables', 'Supports motifs',
       'Motifs detectés'],
      dtype='object')

In [61]:
chekpca = pd.concat([chekpca1, chekpca2], axis=0)

In [62]:
#chekpca.to_excel("../data/serveur/Chickenpox.xlsx", index=False)

In [79]:
cargo_acp = pd.read_csv("../new/Cargo_acp.csv", sep=";")

In [81]:
cargo = pd.read_csv("../new/Cargo_clean.csv", sep=";")

In [85]:
#cargo.sort_values("Support").to_excel("../data/serveur/Cargo.xlsx", index=False)

In [88]:
#cargo_acp.sort_values("Support").to_excel("../data/serveur/Cargo_PCA.xlsx", index=False)